"""Add ForeignKey between Position and Position_year

Revision ID: 0a7dcc1ff478
Revises: 9790b34d9a12
Create Date: 2025-10-30 18:56:53.462698

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0a7dcc1ff478'
down_revision: Union[str, Sequence[str], None] = '9790b34d9a12'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_racers_id'), table_name='racers')
    op.drop_table('racers')
    op.create_index(op.f('ix_position_id'), 'position', ['id'], unique=False)
    op.alter_column('team', 'name',
               existing_type=sa.VARCHAR(length=15),
               type_=sa.String(length=50),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('team', 'name',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=15),
               existing_nullable=False)
    op.drop_index(op.f('ix_position_id'), table_name='position')
    op.create_table('racers',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=15), autoincrement=False, nullable=False),
    sa.Column('team_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['team_name'], ['team.name'], name=op.f('racers_team_name_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('racers_pkey'))
    )
    op.create_index(op.f('ix_racers_id'), 'racers', ['id'], unique=False)
    # ### end Alembic commands ###
