"""migration

Revision ID: 19421a510241
Revises: 
Create Date: 2025-10-18 14:05:22.731908

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '19421a510241'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('car_team', sa.Column('id', sa.Integer(), nullable=False))
    op.add_column('car_team', sa.Column('team_name', sa.String(), nullable=True))
    op.add_column('car_team', sa.Column('car_model', sa.String(), nullable=True))
    op.create_index(op.f('ix_car_team_id'), 'car_team', ['id'], unique=False)
    op.drop_constraint(op.f('car_team_car_id_fkey'), 'car_team', type_='foreignkey')
    op.drop_constraint(op.f('car_team_team_id_fkey'), 'car_team', type_='foreignkey')
    op.create_foreign_key(None, 'car_team', 'car', ['car_model'], ['model'])
    op.create_foreign_key(None, 'car_team', 'team', ['team_name'], ['name'])
    op.drop_column('car_team', 'team_id')
    op.drop_column('car_team', 'car_id')
    op.add_column('position_year', sa.Column('id', sa.Integer(), nullable=False))
    op.alter_column('position_year', 'winner_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('position_year', 'racers_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('position_year', 'position')
    op.add_column('racers', sa.Column('team_name', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'racers', 'team', ['team_name'], ['name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'racers', type_='foreignkey')
    op.drop_column('racers', 'team_name')
    op.add_column('position_year', sa.Column('position', sa.INTEGER(), autoincrement=False, nullable=False))
    op.alter_column('position_year', 'racers_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('position_year', 'winner_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('position_year', 'id')
    op.add_column('car_team', sa.Column('car_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('car_team', sa.Column('team_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'car_team', type_='foreignkey')
    op.drop_constraint(None, 'car_team', type_='foreignkey')
    op.create_foreign_key(op.f('car_team_team_id_fkey'), 'car_team', 'team', ['team_id'], ['id'])
    op.create_foreign_key(op.f('car_team_car_id_fkey'), 'car_team', 'car', ['car_id'], ['id'])
    op.drop_index(op.f('ix_car_team_id'), table_name='car_team')
    op.drop_column('car_team', 'car_model')
    op.drop_column('car_team', 'team_name')
    op.drop_column('car_team', 'id')
    # ### end Alembic commands ###
