"""Add position_id ForeignKey to position_year

Revision ID: 2ec75671a093
Revises: 0a7dcc1ff478
Create Date: 2025-10-30 19:01:08.855680

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2ec75671a093'
down_revision: Union[str, Sequence[str], None] = '0a7dcc1ff478'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('position', sa.Column('title', sa.String(length=50), nullable=False))
    op.drop_column('position', 'year')
    op.add_column('position_year', sa.Column('position_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'position_year', 'position', ['position_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'position_year', type_='foreignkey')
    op.drop_column('position_year', 'position_id')
    op.add_column('position', sa.Column('year', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('position', 'title')
    # ### end Alembic commands ###
