"""remove unique constraint from team name

Revision ID: 712777b333de
Revises: 9b7a0c014f5f
Create Date: 2025-10-31 10:20:13.353204

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '712777b333de'
down_revision: Union[str, Sequence[str], None] = '9b7a0c014f5f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('team_name_key'), 'team', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('team_name_key'), 'team', ['name'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
