"""fix relationships and foreign keys

Revision ID: 9b7a0c014f5f
Revises: 2ec75671a093
Create Date: 2025-10-31 10:16:18.620766

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9b7a0c014f5f'
down_revision: Union[str, Sequence[str], None] = '2ec75671a093'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_position_year_id'), table_name='position_year')
    op.drop_table('position_year')
    op.drop_index(op.f('ix_car_team_id'), table_name='car_team')
    op.drop_table('car_team')
    op.drop_index(op.f('ix_position_id'), table_name='position')
    op.drop_table('position')
    op.alter_column('winner_result', 'winner_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('winner_result', 'racer_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('winner_result', 'points',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint(op.f('winner_result_winner_id_fkey'), 'winner_result', type_='foreignkey')
    op.create_foreign_key(None, 'winner_result', 'winner', ['winner_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'winner_result', type_='foreignkey')
    op.create_foreign_key(op.f('winner_result_winner_id_fkey'), 'winner_result', 'winner', ['winner_id'], ['id'], ondelete='CASCADE')
    op.alter_column('winner_result', 'points',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('winner_result', 'racer_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('winner_result', 'winner_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_table('position',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('position_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='position_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index(op.f('ix_position_id'), 'position', ['id'], unique=False)
    op.create_table('car_team',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('team_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('car_model', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['car_model'], ['car.model'], name=op.f('car_team_car_model_fkey')),
    sa.ForeignKeyConstraint(['team_name'], ['team.name'], name=op.f('car_team_team_name_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('car_team_pkey'))
    )
    op.create_index(op.f('ix_car_team_id'), 'car_team', ['id'], unique=False)
    op.create_table('position_year',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('year', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('racers_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('point', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('position_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['position_id'], ['position.id'], name=op.f('position_year_position_id_fkey')),
    sa.ForeignKeyConstraint(['racers_id'], ['racer.id'], name=op.f('position_year_racers_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('position_year_pkey'))
    )
    op.create_index(op.f('ix_position_year_id'), 'position_year', ['id'], unique=False)
    # ### end Alembic commands ###
